name: parser[#LSO-#LinSpisokObhod]

on:
  schedule:
    - cron: '*/30 * * * *'   # каждые 30 минут
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run config collector
      run: python "parser[LSO-LinSpisokObhod].py"
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "LinSpisokObhod PARSERBOT"
        git add configs/ lists/ collector.log README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Обновление конфигов прошло успешно ($(date +'%Y-%m-%d %H:%M:%S'))"
        git push
